### PR TITLE
Updating encrypted_strings dependency to come from RubyGems

### PR DESCRIPTION
**Pull request by mross22**
The github repository 'better-forks/encrypted_strings' no longer exists so the one click deploy to Heroku (and presumably any other install) doesn't work.

Updating to install straight from RubyGems.

### CODE REVIEW

**Comment by mross22** [comment]
@bih tagging so you see this.  It looks like this library is mostly unmaintained (and simple enough that it doesn't require maintenance) but since its linked from the Spotify dev docs (https://developer.spotify.com/documentation/ios/quick-start/objective-c/) it would be great to get the one click deploy working again!

**Comment by david03g** [comment]
> @bih tagging so you see this. It looks like this library is mostly unmaintained (and simple enough that it doesn't require maintenance) but since its linked from the Spotify dev docs (https://developer.spotify.com/documentation/ios/quick-start/objective-c/) it would be great to get the one click deploy working again!

**Comment by romariomkk** [comment]
@bih Please, merge this as Heroku deploy is so much needed

**Comment by StephanieSantana** [comment]
@bih Please do update this as many have mentioned that the Spotify documentation points directly here.

**Review by bih — APPROVED** [review]

**Comment by bih** [comment]
Merged! Sorry for the delay folks. I'll keep an eye out over the next few days. Let me know if there's anything else I can help with!

**Pull request merged**
